[assembly: System.Reflection.AssemblyCompany("Renowned Games")]
[assembly: System.Reflection.AssemblyTitle("Apex.Demo")]
[assembly: System.Reflection.AssemblyVersion("2.5.0")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2020-2023 Renowned Games All rights reserved.")]
[assembly: UnityEngine.Scripting.Preserve]