[assembly: System.Reflection.AssemblyCompany("Renowned Games")]
[assembly: System.Reflection.AssemblyTitle("ExLib")]
[assembly: System.Reflection.AssemblyVersion("1.0.0")]
[assembly: System.Reflection.AssemblyCopyright("Copyright Renowned Games All rights reserved.")]
[assembly: UnityEngine.Scripting.Preserve]
