[assembly: System.Reflection.AssemblyCompany("Renowned Games")]
[assembly: System.Reflection.AssemblyTitle("AITree.PerceptionSystem")]
[assembly: System.Reflection.AssemblyVersion("1.2.0")]
[assembly: System.Reflection.AssemblyCopyright("Copyright 2022-2023 Renowned Games All rights reserved.")]
[assembly: UnityEngine.Scripting.Preserve]